.TH FORECAST 1 forecast\-git

.SH NAME
forecast \- query weather forecasts from forecast.io

.SH SYNOPSIS
.B forecast
[c:dhL:l:m:rv] [OPTIONS]

.SH DESCRIPTION
forecast is a query program for the forecast.io weather information API.
It provides a command line interface for displaying weather data for a
configurable location.
.P
forecast outputs UTF-8 encoded plain text to stdout. The data is laid
out to be easily readable.

.SH HOMEPAGE
The project's homepage is located at https://github.com/2ion/forecast.

